name: Deploy to GCS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.1.0"

      - name: Initialize Terraform
        id: init
        run: terraform init -backend-config="bucket=leaflet-terraform-state" -backend-config="prefix=terraform/state"
        working-directory: ./terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: ./terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Authenticate with Google Cloud
        run: |
          echo $GOOGLE_CREDENTIALS > /tmp/google-credentials.json
          gcloud auth activate-service-account --key-file=/tmp/google-credentials.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Deploy to GCS
        run: |
          gsutil -m rsync -r ./frontend gs://leaflet-site

      - name: Configure GCS Bucket for Static Website
        run: |
          gsutil web set -m index.html -e index.html gs://leaflet-site
